name: VM
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Build and run the test VM
        run: |
          nix run .#vm-24-05 -- -daemonize -display none

      - name: Test
        run: |
          nix run .#vm-ssh -- cd /src; nix build .#vm-ssh
